# Generated by Django 4.1.1 on 2022-09-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0003_contact_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messages',
        ),
    ]
